### PR TITLE
Adds documentation, fixes typos, consolidates tests, increases coverage, Refactors and Cleans up code

### LINKED ISSUE #69: Fix Typos
Small typos in `Probability.java`

- Second constructor of Probability: `@param` numerator's description has a typo, Numberator.
- addNumerator function: `@param` num's description has a typo, numereator.
- compareTo function: `@return`'s description has a typo, Probabiliy.

Typos in `Bayes.java`: probabilty is used instead of probability.

### PR DESCRIPTION
**Pull request by avidant**
Closes #69

### CODE REVIEW

File: src/test/java/runner/utilTestClasses/TestRunner.java [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
-import edu.uw.cse.testbayes.runner.IndividualClassRunner;
+import edu.uw.cse.testbayes.runner.TestBayesIndividualClassRunner;
 import org.junit.Ignore;
 import org.junit.runner.RunWith;
-import org.junit.runners.*;
+import org.junit.runners.Suite;
 
 @Ignore
-@RunWith(Suite.class)
+@RunWith(TestBayesIndividualClassRunner.class)
```
Comment (avidant) [inline src/test/java/runner/utilTestClasses/TestRunner.java]: @emayer2 Need you to confirm what class comes into the `@RunWith` annotation

Comment (emayer2) [reply src/test/java/runner/utilTestClasses/TestRunner.java]: I'm doing to change the readme, since our main class is what's going to run suite classes
